tasks:
  - init: npm install
    command: npm run dev
ports:
  - port: 3000
    onOpen: open-preview
  - port: 4040
    onOpen: open-preview
vscode:
  extensions:
    - eamodio.gitlens
    - esbenp.prettier-vscode
    - usernamehw.errorlens
